[book]
authors = ["duykhanh471"]
language = "vi"
multilingual = false
src = "src"
title = "Cấu trúc và diễn giải chương trình máy tính - SICP 2nd."

[build]
build-dir = "public"

[output.html]
mathjax-support = true